    CREATE SEQUENCE MODULE_OPTION_SRL_SEQ;

    CREATE TABLE MODULE_OPTION
    (
      MODULE_IDX             CHAR(20) NOT NULL ,
      MODULE_OPTION_SRL     NUMBER,
      OPTION_NAME            VARCHAR2(150) NOT NULL ,
      OPTION_VALUE           VARCHAR2(150) NULL ,
      OPTION_TITLE           VARCHAR2(150) NULL ,
      OPTION_ORDER           NUMBER(11)
    );

    ALTER TABLE MODULE_OPTION
      ADD CONSTRAINT  MODULE_OPTION_PK PRIMARY KEY (OPTION_NAME, MODULE_IDX);

    CREATE  INDEX MODULE_OPTION_IDX_1 ON MODULE_OPTION (MODULE_IDX   ASC);

    COMMENT ON TABLE MODULE_OPTION IS '모듈 옵션';

    COMMENT ON COLUMN MODULE_OPTION.MODULE_IDX IS '모듈 IDX';
    COMMENT ON COLUMN MODULE_OPTION.MODULE_OPTION_SRL IS '모듈 옵션 번호';
    COMMENT ON COLUMN MODULE_OPTION.OPTION_NAME IS '옵션명';
    COMMENT ON COLUMN MODULE_OPTION.OPTION_VALUE IS '옵션값';
    COMMENT ON COLUMN MODULE_OPTION.OPTION_TITLE IS '이름';
    COMMENT ON COLUMN MODULE_OPTION.OPTION_ORDER IS '순서';