    CREATE SEQUENCE MODULE_IDX_SEQ;

    CREATE TABLE MODULE
    (
      MODULE_IDX           CHAR(20) NOT NULL ,
      MODULE_NAME          VARCHAR2(100) NOT NULL ,
      MODULE_ID            VARCHAR2(100) NOT NULL ,
      BROWSER_TITLE        VARCHAR2(255) NULL ,
      SKIN                 VARCHAR2(100) NULL ,
      LAYOUT_IDX           CHAR(20) NULL,
      REG_DATE             DATE NULL
    );

    ALTER TABLE MODULE
    ADD CONSTRAINT  MODULE_PK PRIMARY KEY (MODULE_IDX);

    ALTER TABLE MODULE
    ADD CONSTRAINT  MODULE_UQ_1 UNIQUE (MODULE_ID);

    COMMENT ON TABLE MODULE IS '모듈';

    COMMENT ON COLUMN MODULE.MODULE_IDX IS '모듈 IDX';
    COMMENT ON COLUMN MODULE.MODULE_NAME IS '모듈명';
    COMMENT ON COLUMN MODULE.MODULE_ID IS '모듈ID';
    COMMENT ON COLUMN MODULE.BROWSER_TITLE IS '브라우저 타이틀';
    COMMENT ON COLUMN MODULE.SKIN IS '스킨';
    COMMENT ON COLUMN MODULE.LAYOUT_IDX IS '레이아웃 IDX';
    COMMENT ON COLUMN MODULE.REG_DATE IS '등록일';