    CREATE TABLE MODULE_OPTIONS
    (
      MODULE_IDX      CHAR(20) NOT NULL ,
      OPTION_NAME            VARCHAR2(150) NOT NULL ,
      OPTION_VALUE           VARCHAR2(150) NULL ,
      OPTION_TITLE           VARCHAR2(150) NULL ,
      OPTION_ORDER             NUMBER(11)
    );

    ALTER TABLE MODULE_OPTIONS
    ADD CONSTRAINT  MODULE_OPTIONS_PK PRIMARY KEY (OPTION_NAME, MODULE_IDX);

    CREATE  INDEX MODULE_OPTIONS_IDX_1 ON MODULE_OPTIONS (MODULE_IDX   ASC);

    COMMENT ON TABLE MODULE_OPTIONS IS '모듈 옵션';

    COMMENT ON COLUMN MODULE_OPTIONS.MODULE_IDX IS '모듈 IDX';
    COMMENT ON COLUMN MODULE_OPTIONS.OPTION_NAME IS '옵션명';
    COMMENT ON COLUMN MODULE_OPTIONS.OPTION_VALUE IS '옵션값';
    COMMENT ON COLUMN MODULE_OPTIONS.OPTION_TITLE IS '이름';
    COMMENT ON COLUMN MODULE_OPTIONS.OPTION_ORDER IS '순서';