    CREATE TABLE TEST
    (
      NAME            VARCHAR2(100) NOT NULL,
      VALUE          VARCHAR2(100) NOT NULL,
      REG_DATE             DATETIME NULL
    );

    ALTER TABLE TEST
    ADD CONSTRAINT  TEST_PK PRIMARY KEY (NAME);

    COMMENT ON TABLE TEST IS '테스트';

    COMMENT ON COLUMN TEST.NAME IS '이름';
    COMMENT ON COLUMN TEST.VALUE IS '값';
    COMMENT ON COLUMN TEST.REG_DATE IS '등록일';