INSERT INTO TEST (NAME, VALUE, REG_DATE) VALUES ( 'test', 'test', SYSDATE);
INSERT INTO TEST (NAME, VALUE, REG_DATE) VALUES ( 'test1', 'testa', SYSDATE);
INSERT INTO TEST (NAME, VALUE, REG_DATE) VALUES ( 'test2', 'testb', SYSDATE);
INSERT INTO TEST (NAME, VALUE, REG_DATE) VALUES ( 'test3', 'testc', SYSDATE);
INSERT INTO TEST (NAME, VALUE, REG_DATE) VALUES ( 'test4', 'testd', SYSDATE);