INSERT INTO MODULE (MODULE_ID, MODULE_NAME, REG_DATE) VALUES ( 'test', 'test', SYSDATE);
INSERT INTO MODULE (MODULE_ID, MODULE_NAME, REG_DATE) VALUES ( 'test2', 'test', SYSDATE);
INSERT INTO MODULE (MODULE_ID, MODULE_NAME, REG_DATE) VALUES ( 'test3', 'test', SYSDATE);
INSERT INTO MODULE (MODULE_ID, MODULE_NAME, REG_DATE) VALUES ( 'test4', 'test', SYSDATE);

INSERT INTO MODULE_OPTION (MODULE_ID, OPTION_NAME, OPTION_VALUE, OPTION_TITLE, OPTION_ORDER) VALUES ( 'test', 'a', '1', 'a', 0);
INSERT INTO MODULE_OPTION (MODULE_ID, OPTION_NAME, OPTION_VALUE, OPTION_TITLE, OPTION_ORDER) VALUES ( 'test', 'b', '2', 'b', 1);